server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki.bidgallery.publicvm.com:3100/loki/api/v1/push

scrape_configs:
- job_name: bidgallery
  static_configs:
  - targets:
      - localhost
    labels:
      job: bidgallery-logs
      app: bidgallery-backend
      environment: production
      __path__: /var/lib/docker/containers/*/*.log