global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bidgallery-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend.bidgallery.publicvm.com']
    scheme: https
    tls_config:
      insecure_skip_verify: true
