global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bidgallery-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
        labels:  
          application: 'bidgallery-backend'
          environment: 'development'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']