name: FullStack CI

on:
  push:
    branches: [main, dev]
    paths-ignore: 
      - '**.md'
      - 'docs/**'
      - '**.txt'
  pull_request:
    branches: [main, dev]

jobs:
  frontend-ci:
    uses: ./.github/workflows/ci/frontend-ci.yml
    secrets: inherit

  backend-ci:
    uses: ./.github/workflows/ci/backend-ci.yml
    secrets: inherit